project:
  type: website
  preview:
    port: 4444
    browser: false   # don’t auto-open a new tab

# Global execution policy: cache + freeze for fast rebuilds
execute:
  cache: true        # use knitr cache for R chunks
  freeze: auto       # only re-execute pages when their source changes

website:
  title: "Grundlagen der Datenanalyse (GDA)"
  page-footer: 
    left: "Copyright 2025, Ilya Zarubin" 
    right: 
      - icon: github
        href: https://github.com/ilyaZar/
      - icon: twitter 
        href: https://x.com/ilyaazarubin
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    logo: assets/logo_hfh.png 
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/orgs/HamburgerFH/dashboard
          - text: Report a Bug
            href: https://github.com/orgs/HamburgerFH/dashboard
      - icon: linkedin
        href: https://www.linkedin.com/school/hamburger-fern-hochschule/
      - icon: youtube
        href: https://www.youtube.com/user/HFHFernhochschule
      - icon: instagram
        href: https://www.instagram.com/hfhfernstudium/
    contents:
      - text: Home
        href: index.qmd
      - text: "---"
      - section: "Studienbrief 1"
        contents:
          - href: ./include/01_programmierung.qmd
            text: "Prommiergrundlagen `R` und Python"
      - section: "Studienbrief 2"
        contents: 
          - href: ./include/02_02_MLR.qmd
            text: "Multiple Lineare Regression"
          - href: ./include/02_03_BLR.qmd
            text: "Binär logistische Regression"
          - href: ./include/02_04_MLR.qmd
            text: "Multinomial logistische Regression"
          - href: ./include/02_05_OLR.qmd
            text: "Ordinal logistische Regression"
      - section: "Studienbrief 3"
        contents: 
          - href: ./include/03_01_TZ.qmd
            text: "Theorie der Zeitreihen"
          - href: ./include/03_02_WGB.qmd
            text: "Wichtige Grundbegriffe"
          - href: ./include/03_03_ZRA_in_R.qmd
            text: "Zeitreihenanalysen in `R`"
          - href: ./include/03_04_BCA.qmd
            text: "Business Cycle Analysen"
          - href: ./include/03_05_AR_GARCH.qmd
            text: "AR-Modelle"
      - section: "Studienbrief 4"
        contents: 
          - href: ./include/04_01_apriori_definitions.qmd
            text: "Assoziationsanalyse"
          - href: ./include/04_02_conjoint.qmd
            text: "Conjoint-Analyse"
      - section: "Studienbrief 5"
        contents: 
          - href: ./include/05_01_paneldaten_effectsmodels.qmd
            text: "Paneldaten und das Effects-Modell"
          - href: ./include/05_02_03_paneldaten_weiteres.qmd
            text: "Wdhl. allgemeiner Konzepte"
          - href: ./include/05_04_FE_modell.qmd
            text: "Schätzung im FE-Modell"
          - href: ./include/05_05_RE_modell.qmd
            text: "Schätzung im RE-Modell"
          - href: ./include/05_06_hausmann.qmd
            text: "Auswahl geeigneteR Paneldatenmodelle: Hausman-Test"
      - text: "---"
      - section: "Altklausuren"
        contents: 
          - href: ./include/99_altklausuren_A1.qmd
            text: "Aufgabentyp 1"
          - href: ./include/99_altklausuren_A2.qmd
            text: "Aufgabentyp 2"
          - href: ./include/99_altklausuren_A3.qmd
            text: "Aufgabentyp 3"
          - href: ./include/99_altklausuren_A4.qmd
            text: "Aufgabentyp 4"
          - href: ./include/99_altklausuren_A5.qmd
            text: "Aufgabentyp 5"
      - text: "---"
      - about.qmd

format:
  html:
    html-math-method: mathjax
    include-in-header:
      - file: mathjax-macros.html
    theme:
      - cosmo
      - brand
      - custom.scss
    css: styles.css
    toc: true